spring:
  profiles:
    active: production

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: nguyenminhdev7@gmail.com
#    password: vndcsohccduamdmd # <-- LƯU Ý ĐỌC KỸ MỤC 1 BÊN DƯỚI
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true # Nên thêm dòng này cho Gmail
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

mqtt:
  broker: tcp://test.mosquitto.org:1883
  client-id: spring-tracker-${random.uuid}
  telemetry-topic: bike/telemetry
  alert-topic: bike/alert

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG